# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d974caad4182a2d3b19841ffc587c6d35bb06c6fb1dff34cd0ed2cf12191516b31c4564ea169c18cd2ac4f666a8616f16067a9e21f330bf556e9399e0891d06

test:
  secret_key_base: d97216995d399bd2d5e5fa3efb99186dea5c48c15e13da8538758da2d9606edcc77c31d4ba4a79c3255c67e05b625bfbd90d67a0344e5918cf9fb81d433d9db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
